sudo: required

services:
  - docker

install:
  #- docker build -t eosrate/demux ./services/demux
  - docker build -t eosrate/frontend ./services/frontend
  - docker build -t eosrate/hapi ./services/hapi

script:
  #- docker run eosrate/demux yarn lint
  - docker run eosrate/frontend yarn lint
  - docker run eosrate/hapi yarn lint
