---
# tasks file for create_server_do
- name: create a new server {{ SERVER_NAME }} on DigitalOcean
  digital_ocean_droplet:
    state: present
    name: "{{ SERVER_NAME }}"
    oauth_token: "{{ TOKEN }}"
    size: "{{ SIZE }}"
    region: sfo2
    image: "{{ IMAGE }}"
    wait_timeout: 1500
  register: my_droplet

- debug:
    msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"

- debug: 
    msg: Register server id within {{ DEL_VAR }} file

- lineinfile:
    path: "{{ DEL_VAR }}"
    regexp: '^SERVER_ID: '
    line: 'SERVER_ID: {{ my_droplet.data.droplet.id }}'
