apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hapi
  name: hapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hapi
    spec:
      containers:
      - image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HAPI}:latest
        imagePullPolicy: "Always"
        name: eosrate-hapi
        envFrom:
        - configMapRef:
            name: hapi-config
        ports:
        - containerPort: 9090
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      restartPolicy: Always
