-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."comment" add column "total_dislike" integer
--  not null default '0';
