apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: demux
  name: demux
spec:
  ports:
  - name: "3030"
    port: 3030
    targetPort: 3030
  selector:
    io.kompose.service: demux
