name: Build images from latest master branch

on:
  push:
    tags:
      - v*

jobs:
  create-master-image:
    name:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USER }} \
            --password-stdin

      - name: Install node module dependencies
        run: |
          cd services/hapi
          yarn
          cd ../frontend
          yarn
          cd ../..

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          # general
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          BRANCH: production
          NAMESPACE: mainnet-eosrate
          # webapp
          REACT_APP_GRAPHQL_HTTP_URL: https://graphql.eosrate.io/v1/graphql
          REACT_APP_GRAPHQL_WS_URL: wss://graphql.eosrate.io/v1/graphql
          REACT_APP_EOS_API_URL: https://api.eosio.cr
          REACT_APP_EOS_API_HOST: api.eosio.cr
          REACT_APP_EOS_API_PORT: 443
          REACT_APP_EOS_API_PROTOCOL: https
          REACT_APP_EOS_CHAIN_ID: aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906
          REACT_APP_BLOCK_EXPLORER: https://bloks.io

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          BRANCH: production
          NAMESPACE: mainnet-eosrate
          INGRESS_HOST: eosrate.io
          INGRESS_GRAPHQL_HOST: graphql.eosrate.io
          # webapp
          REACT_APP_GRAPHQL_HTTP_URL: https://graphql.eosrate.io/v1/graphql
          REACT_APP_GRAPHQL_WS_URL: wss://graphql.eosrate.io/v1/graphql
          REACT_APP_EOS_API_URL: https://api.eosio.cr
          REACT_APP_EOS_API_HOST: api.eosio.cr
          REACT_APP_EOS_API_PORT: 443
          REACT_APP_EOS_API_PROTOCOL: https
          REACT_APP_EOS_CHAIN_ID: aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906
          REACT_APP_BLOCK_EXPLORER: https://bloks.io
          # postgres
          DATABASE_DIRECTORY: database
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          # hapi
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}
          EOS_API_ENDPOINT: https://api.eosio.cr
          HAPI_SERVER_ADDRESS: 0.0.0.0
          HAPI_SERVER_PORT: 9090
          PROXY_INFO_CONTRACT_CODE: regproxyinfo
          PROXY_INFO_CONTRACT_SCOPE: regproxyinfo
          # hasura
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_ACTION_BASE_URL: http://hapi:9090
          # pgweb
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Setup and deploy kubernetes environment
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: mainnet-eosrate
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
